name: Python Tox


on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10.5 ]

    steps:
      - uses: knowsuchagency/poetry-install@v2
      - name: Poetry Install
