- name: Setup Poetry
  # You may pin to the exact commit or the version.
  # uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844
  uses: Gr1N/setup-poetry@v8
  with:
    # Allow to install prerelease versions of Poetry
    poetry-preview: # optional, default is false
    # Poetry version to use, if version is not provided then latest stable version will be used
    poetry-version: # optional
