name: Compile sphinx documentation

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10"]
        poetry-version: ["1.4.0"]
        os: [ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install dependecies
        run: | 
              poetry install

      - name: doc_compile
        run: poetry run task html_docs
